### PR TITLE
Fixes Issue 14, readline package not working on Windows Operating Systems.

### PR DESCRIPTION
**Pull request by Spiritgunn22**

### CODE REVIEW

**Comment by daegontaven** [comment]
@Spiritgunn22 Thank you for your first full pull request ! Please make a feature branch before creating a pull request. We follow [Github Flow](https://guides.github.com/introduction/flow/) here. I've added that detail to the contribution guidelines.

**Comment by Spiritgunn22** [comment]
I work on a Windows 7 Machine and installing pyreadline seamlessly enables the program to work with out having to add any additional imports or code. I could verify on windows 8 and 10 or if that still wouldn't make you comfortable I'll look into the list method.

**Comment by Spiritgunn22** [comment]
I also apologize for not creating a branch. I read an outdated guide that said bug fixes should just be done from a branch of the original repo and new features should get a branch. It won't happen again.

**Comment by daegontaven** [comment]
@Spiritgunn22 Thank you for looking into this. There's no need to apologize. I've wanted to make it compatible on windows machines for a while now. However we only need it to make it work on Windows 10 and later. Anything that comes before Windows 10 is just a side benefit. In the case of Windows 7, it was [EOL'd ](https://en.wikipedia.org/wiki/End-of-life_(product)) on [January 13, 2015](https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet).

Please understand that it I am at fault here for not having properly documented the workflow. I will have to get around to it as soon as one of the major bugs have been solved. So in a way you're already contributing by reminding me of missing documentation.

We do our testing for windows automatically using [AppVeyor.](https://ci.appveyor.com/project/daegontaven/alphahooks) Please create a pull request once again to see if your changes pass the tests. Here is an [example](https://ci.appveyor.com/project/daegontaven/alphahooks/build/job/79ikwaovyqblb29p) of the tests failing to run because `readline` cannot be imported.

Note that while using `pyreadline` may or may not fix the issue at stake, it will most certainly be an additional dependency. More dependencies means it's harder to maintain code. So in the short term it will fix the problem(provided it passes the tests) so that we can continue with testing on windows. However, I will not be able to close the issue even if I do decide to merge it. So please please omit [closing keywords](https://help.github.com/articles/closing-issues-using-keywords/) from your commit description. 

Thank you for the help!

:raised_hands:

**Pull request closed without merging**
